name: Lint

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9
      - name: Install project dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[test]
      - name: Run Flake8
        run: flake8 --ignore E203,E501,W503
      - name: Black code style
        run: black --check --target-version py36 brain_reproducibility
      - name: Check import order with isort
        run: isort . --check --diff
      - name: Type check with PyType
        run: pytype brain_reproducibility --jobs auto

